terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/usr/shared_apps/packages/sge-8.1.8-1/default/spool/comp05-00/job_scripts/7908951: line 7: 31762 Aborted                 ./a.out
